packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
  workerd: true
