services:
  postgres:
    image: postgres:17
    container_name: ai-travel-planner-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ai-travel-planner
      POSTGRES_PASSWORD: ai-travel-planner
      POSTGRES_DB: ai-travel-planner
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
